server:
  port: 8081

spring:
  config:
    import:
      - classpath:queue-events.yml
# H2 Database Configuration
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:orderdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true